CREATE TABLE CLIENT (
    ID_CLIENT INT PRIMARY KEY,
    NUME VARCHAR(50) NOT NULL,
    PRENUME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    TELEFON VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE ANGAJAT (
    ID_ANGAJAT INT PRIMARY KEY,
    NUME VARCHAR(50) NOT NULL,
    PRENUME VARCHAR(50) NOT NULL,
    DATA_ANGAJARE DATE NOT NULL,
    POZITIE VARCHAR(50) NOT NULL
);

CREATE TABLE ADMIN (
    ID_ADMIN INT PRIMARY KEY,
    NUME VARCHAR(50) NOT NULL,
    PRENUME VARCHAR(50) NOT NULL,
    DATA_ANGAJARE DATE NOT NULL,
    NIVEL_ACCESS VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUS (
    ID_PRODUS INT PRIMARY KEY,
    NUME VARCHAR(50) NOT NULL,
    PRET DECIMAL(10, 2) NOT NULL CHECK (PRET >= 0),
    ID_CATEGORIE INT NOT NULL
);

CREATE TABLE BON (
    ID_BON INT PRIMARY KEY,
    DATA_BON DATE NOT NULL,
    ID_CLIENT INT NOT NULL,
    ID_ANGAJAT INT NOT NULL,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT(ID_ANGAJAT)
);

CREATE TABLE DETALIIBON (
    ID_DETALIUBON INT PRIMARY KEY,
    ID_BON INT NOT NULL,
    ID_PRODUS INT NOT NULL,
    CANTITATE INT NOT NULL CHECK (CANTITATE > 0),
    PRET_VANZARE DECIMAL(10, 2) NOT NULL CHECK (PRET_VANZARE >= 0),
    FOREIGN KEY (ID_BON) REFERENCES BON(ID_BON),
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
);

CREATE TABLE NOTIFICARICLIENT (
    ID_NOTIFICARE INT PRIMARY KEY,
    ID_CLIENT INT NOT NULL,
    MESAJ VARCHAR2(4000) NOT NULL,
    DATA DATE NOT NULL,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

CREATE TABLE NOTIFICARIANGAJAT (
    ID_NOTIFICARE INT PRIMARY KEY,
    ID_ANGAJAT INT NOT NULL,
    MESAJ VARCHAR2(4000) NOT NULL,
    DATA DATE NOT NULL,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT(ID_ANGAJAT)
);

CREATE TABLE NOTIFICARIADMIN (
    ID_NOTIFICARE INT PRIMARY KEY,
    ID_ADMIN INT NOT NULL,
    MESAJ VARCHAR2(4000) NOT NULL,
    DATA DATE NOT NULL,
    FOREIGN KEY (ID_ADMIN) REFERENCES ADMIN(ID_ADMIN)
);

CREATE TABLE SCHIMB (
    ID_SCHIMB INT PRIMARY KEY,
    ID_ANGAJAT INT NOT NULL,
    DATA_START TIMESTAMP NOT NULL,
    DATA_END TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJAT(ID_ANGAJAT)
);

CREATE TABLE INVENTAR (
    ID_INVENTAR INT PRIMARY KEY,
    ID_PRODUS INT NOT NULL,
    CANTITATE INT NOT NULL CHECK (CANTITATE >= 0),
    DATA_ACTUALIZARE TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
);

CREATE TABLE PROMOTII (
    ID_PROMOTIE INT PRIMARY KEY,
    DESCRIERE VARCHAR2(4000) NOT NULL,
    DATA_INCEPUT TIMESTAMP NOT NULL,
    DATA_SFARSIT TIMESTAMP NOT NULL
);

CREATE TABLE DETALIIPROMOTII (
    ID_DETALIU INT PRIMARY KEY,
    ID_PROMOTIE INT NOT NULL,
    ID_PRODUS INT NOT NULL,
    REDUCERE DECIMAL(10, 2) NOT NULL CHECK (REDUCERE >= 0 AND REDUCERE <= 1),
    FOREIGN KEY (ID_PROMOTIE) REFERENCES PROMOTII(ID_PROMOTIE),
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
);

CREATE TABLE CATEGORIIPRODUSE (
    ID_CATEGORIE INT PRIMARY KEY,
    NUME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE METODEPLATA (
    ID_METODA INT PRIMARY KEY,
    DESCRIERE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PLATI (
    ID_PLATA INT PRIMARY KEY,
    ID_BON INT NOT NULL,
    ID_METODA INT NOT NULL,
    SUMA DECIMAL(10, 2) NOT NULL CHECK (SUMA >= 0),
    DATA TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_BON) REFERENCES BON(ID_BON),
    FOREIGN KEY (ID_METODA) REFERENCES METODEPLATA(ID_METODA)
);

CREATE TABLE RETURURI (
    ID_RETUR INT PRIMARY KEY,
    ID_DETALIU INT NOT NULL,
    MOTIV VARCHAR2(4000) NOT NULL,
    DATA DATE NOT NULL,
    FOREIGN KEY (ID_DETALIU) REFERENCES DETALIIBON(ID_DETALIUBON)
);

CREATE TABLE FURNIZORI (
    ID_FURNIZOR INT PRIMARY KEY,
    NUME VARCHAR(50) NOT NULL UNIQUE,
    ADRESA VARCHAR(100) NOT NULL,
    TELEFON VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE COMENZIFURNIZORI (
    ID_COMANDA INT PRIMARY KEY,
    ID_FURNIZOR INT NOT NULL,
    DATA_COMANDA TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_FURNIZOR) REFERENCES FURNIZORI(ID_FURNIZOR)
);

CREATE TABLE DETALIICOMENZI (
    ID_DETALIU INT PRIMARY KEY,
    ID_COMANDA INT NOT NULL,
    ID_PRODUS INT NOT NULL,
    CANTITATE INT NOT NULL CHECK (CANTITATE > 0),
    PRET DECIMAL(10, 2) NOT NULL CHECK (PRET >= 0),
    FOREIGN KEY (ID_COMANDA) REFERENCES COMENZIFURNIZORI(ID_COMANDA),
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
);

CREATE TABLE CARDURILOYALITATE (
    ID_CARD INT PRIMARY KEY,
    ID_CLIENT INT NOT NULL,
    NUMAR_CARD VARCHAR(50) NOT NULL UNIQUE,
    PUNCTE INT NOT NULL CHECK (PUNCTE >= 0),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

CREATE TABLE CUPOANE (
    ID_CUPON INT PRIMARY KEY,
    DESCRIERE VARCHAR2(4000) NOT NULL,
    DATA_INCEPUT TIMESTAMP NOT NULL,
    DATA_SFARSIT TIMESTAMP NOT NULL,
    VAL_REDUCERE DECIMAL(10, 2) NOT NULL CHECK (VAL_REDUCERE >= 0 AND VAL_REDUCERE <= 100)
);

CREATE TABLE CLIENTICUPOANE (
    ID_CLIENT INT NOT NULL,
    ID_CUPON INT NOT NULL,
    DATA_ATRIBUIRE TIMESTAMP NOT NULL,
    DATA_UTILIZARE TIMESTAMP,
    PRIMARY KEY (ID_CLIENT, ID_CUPON),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY (ID_CUPON) REFERENCES CUPOANE(ID_CUPON)
);

CREATE TABLE REDUCERITEMPORARE (
    ID_DISCOUNT INT PRIMARY KEY,
    ID_PRODUS INT NOT NULL,
    DATA_INCEPUT TIMESTAMP NOT NULL,
    DATA_SFARSIT TIMESTAMP NOT NULL,
    REDUCERE DECIMAL(10, 2) NOT NULL CHECK (REDUCERE >= 0 AND REDUCERE <= 1),
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUS(ID_PRODUS)
);